### PR TITLE
fixed FallBack Image for campaigns in Campaign Management #282

### LINKED ISSUE #282: FallBack Image for campaigns in Campaign Management
# 🐛 Bug Report: Missing Fallback Image for Campaigns Without Cover Images

## 📋 Issue Description

**Problem**: Campaigns created without cover images display broken image placeholders or empty spaces in the campaign management interface and public campaign views, creating a poor user experience.

**Current Behavior**: 
- When a campaign is created without uploading a cover image, no fallback image is displayed
- This results in broken image elements or empty spaces in:
  - Campaign management dashboard
  - Public campaign display pages
  - Campaign cards/listings

Image

**Expected Behavior**:
- Display a default placeholder image when no cover image is provided
- Maintain consistent visual layout across all campaign displays
- Provide a professional appearance even for campaigns without custom images

## 🔍 Root Cause Analysis

The issue stems from the lack of fallback image handling in the `ImageWithFallback` component and campaign display logic. When `campaign.coverImageUrl` is empty or null, no default image is rendered.

### Primary Files:
- `src/shared/ui/figma/ImageWithFallback.tsx` - Main image component
- `src/views/admin/CampaignManagement.tsx` - Campaign management interface
- `src/views/campaigns/CampaignScreen.tsx` - Public campaign display

### Supporting Files:
- `public/` - Location for default campaign image asset
- `src/shared/constants/` - Default image path constants

### Step 1: Add Default Campaign Image Asset
1. Add a default campaign placeholder image to `public/images/`
2. Recommended filename: `default-campaign-cover.jpg` or `campaign-placeholder.svg`
3. Image should be professional, neutral, and match brand guidelines

### Step 2: Update ImageWithFallback Component
Enhance the component to accept and use fallback images:

```typescript
// src/shared/ui/figma/ImageWithFallback.tsx
interface ImageWithFallbackProps {
  src?: string;
  alt: string;
  fallbackSrc?: string; // New prop for fallback image
  className?: string;
}

export function ImageWithFallback({ 
  src, 
  alt, 
  fallbackSrc = '/images/default-campaign-cover.jpg', // Default fallback
  className 
}: ImageWithFallbackProps) {
  const [imgSrc, setImgSrc] = useState(src || fallbackSrc);
  const [hasError, setHasError] = useState(false);

  useEffect(() => {
    setImgSrc(src || fallbackSrc);
    setHasError(false);
  }, [src, fallbackSrc]);

  const handleError = () => {
    if (!hasError && imgSrc !== fallbackSrc) {
      setHasError(true);
      setImgSrc(fallbackSrc);
    }
  };

  return (
    <img
      src={imgSrc}
      alt={alt}
      className={className}
      onError={handleError}
    />
  );
}

### PR DESCRIPTION
**Pull request by yuvraj-shishodia**
## Description
  Introduces a shared fallback image for campaigns that do not have a cover image.
  This prevents broken image placeholders and empty layouts by centralizing the
  placeholder path and improving image fallback handling. Campaign-related UIs
  now render consistently across admin, public, donation, and kiosk flows even
  when a campaign does not have a custom cover image.

  ---

## Issue Link
https://github.com/YNVSolutions/SwiftCause_Web/issues/282
Fixes #282

---

### Before
Screenshot 2025-12-16 024502
Screenshot 2025-12-16 024531
Screenshot 2025-12-16 024556

### After
Screenshot 2025-12-16 024828
Screenshot 2025-12-16 024805
Screenshot 2025-12-16 024731

---

  ## Changes
  - Added shared placeholder constant `DEFAULT_CAMPAIGN_IMAGE` in
    `src/shared/config/constants.ts`
  - Enhanced `ImageWithFallback` to:
    - Accept a `fallbackSrc` prop
    - Use the fallback when `src` is missing or fails to load
    - Prevent infinite fallback loops
  - Wired fallback image usage across campaign UIs:
    - Shared and entity `CampaignCard` components
    - Campaign screens and donation selection flows
    - Admin campaign list
    - Kiosk campaign assignment dialog
  - Added a **Remove** button in Admin Campaign Management to clear campaign
    cover image selection/preview and rely on the fallback
  - Updated kiosk campaign assignment cards (assigned / available / global)
    to consistently use `ImageWithFallback` with the placeholder

  ---

  ## Implementation Details

  ### Shared Placeholder
  - Centralized the campaign placeholder path via `DEFAULT_CAMPAIGN_IMAGE`
  - Placeholder asset expected at `/campaign-placeholder.jpg` under `public/`

  ### Image Fallback Handling
  - Handles missing or null image sources
  - Falls back on image load errors
  - Guards against repeated fallback render loops

  ### Admin & Kiosk Behavior
  - Admins can remove campaign cover images without breaking UI
  - Kiosk campaign assignment views render consistent placeholders
  - Existing kiosk campaign display limit remains unchanged
    (`maxCampaignsDisplay`)

  ---

  ## Acceptance Criteria Met
  - [x] Campaigns without cover images render a placeholder instead of broken images
  - [x] Fallback image used when image loading fails
  - [x] No infinite image reload loops introduced
  - [x] Admin cover image removal falls back correctly
  - [x] Kiosk campaign cards display placeholders consistently
  - [x] No change to kiosk campaign display limits

  ---

  ## Issue Reference
  Closes #282

### CODE REVIEW

File: src/views/admin/CampaignManagement.tsx [hunk 1]
```diff
@@ -384,138 +379,54 @@ const CampaignDialog = ({
...
-        prev.filter((file) => URL.createObjectURL(file) !== imageToDelete)
-      );
-      alert("Image deleted successfully.");
+      await deleteFile(imageToDelete);
+      removeFromState();
     } catch (error) {
-      console.error("Error deleting gallery image:", error);
-      alert("Failed to delete image. Please try again.");
+      // Ignore if the file is already gone; otherwise log
+      // @ts-ignore
```
Comment (CodrJitesh) [inline src/views/admin/CampaignManagement.tsx]: Not a good practice to use @ts-ignore in the code.

Comment (yuvraj-shishodia) [reply src/views/admin/CampaignManagement.tsx]: The @ts-ignore was replaced with a typed error code check, so behavior is unchanged apart from stricter typing. No tests were run, but functionality should remain intact; you can spot-check gallery image deletion and any screens showing broken images to confirm.
